# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9483f9969f0eeb1f90d5f18ed1c77d26179d495d41fb63b4fff7da55822bd949399b077fb0172a0ddbd7cb2e58a6801e87228f406083d35ca7967a313a4063b

test:
  secret_key_base: 3f895400b6c3fc7241017ef2ddaa7c16edcaa205e5489a32e9546246d92ddd820a7cb9059af945aa28edf47f8f7bf425b2c73050094dd6bff0496aff195a0300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
